server:
  port: 10010
registry:
  host: localhost
  port: 10000


management:
  endpoint:
    consul:
      enabled: true
    health:
      show-details: always
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  application:
    name: im-cache
  profiles:
    include: consul,redis
